version: '3.8'

services:
  app:
    build: .                # Build the image from the Dockerfile in the current directory
    ports:
      - "8084:8083"         # Updated to match PORT in .env
    env_file:
      - .env                # Load environment variables from .env file
    depends_on:
      - mongo               # Wait for the mongo service to be ready before starting
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - "27020:27017"       # Map host port 27018 to container port 27017
    volumes:
      - mongo-data:/priti/data/db

volumes:
  mongo-data:                # Define the named volume for MongoDB data